feat: Add tags & metadata for openai instrumentation
Chainlit/literal-docs pull request #32
Opened 2024-04-26 12:49 UTC by Granipouss

Documentation for https://github.com/Chainlit/typescript-client/pull/17 & https://github.com/Chainlit/python-client/pull/63

2024-05-04 12:56 UTC, constantinidan requested changes

2024-05-04 12:56 UTC, constantinidan commented on integrations/openai.mdx
> +    literal_tags=["tag1", "tag2"],
literalai_tags ?

2024-05-06 09:52 UTC, Granipouss commented on integrations/openai.mdx
> +    literal_tags=["tag1", "tag2"],
https://github.com/Chainlit/python-client/pull/67

2024-05-06 10:58 UTC, laura-ham approved these changes

2024-05-07 08:27 UTC, constantinidan approved these changes

2024-05-07 08:43 UTC, merged